# Generated by Django 5.2.10 on 2026-01-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название')),
                ('director', models.CharField(verbose_name='Режиссёр')),
                ('genre', models.CharField(blank=True, verbose_name='Жанр')),
                ('releaseYear', models.IntegerField(verbose_name='Год выхода')),
                ('poster', models.ImageField(blank=True, upload_to='movies_images', verbose_name='Постер')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
